config/routes.rb
Rails.application.routes.draw do

  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :microposts do
    resources :comments do
      member do
        get :reply
      end
    end
  end


  resources :users do
    member do
      get :following, :followers, :likeindex
    end
  end

  resources :likes
  resources :relationships, only: [:create, :destroy]
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div class="error_explanation">
        <div class="alert alert-danger">
            The form contain <%= pluralize(object.errors.count, "error") %>
        </div>
        <ul>
            <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_form.html.erb
<%= form_for(@user) do |f| %>
    <%= render"shared/error_messages", object: f.object%>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control'  %>

    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control'  %>

    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control'  %>

    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation, class: 'form-control'  %>

    <%= f.submit "Create my account", class: "btn btn-primary" %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
      <%= f.text_area :content, placeholder: "Compose new micropost..." %>
    </div>
    <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
    <a href="<%= following_user_path(@user) %>">
        <strong id="following" class="stat">
            <%= @user.following.count %>
        </strong>
        following
    </a>
    <a href="<%= followers_user_path(@user) %>">
        <strong id="followers" class="stat">
            <%= @user.followers.count %>
        </strong>
        followers
    </a>
    <a href="<%= likeindex_user_path(@user) %>">
        <strong id="likeindex" class="stat">
            <%= @user.likes.count %>
        </strong>
        likes
    </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>