config/routes.rb
Rails.application.routes.draw do

  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :microposts do
    resources :comments do
      member do
        get :reply
      end
    end
  end


  resources :users do
    member do
      get :following, :followers, :likeindex
    end
  end

  resources :likes
  resources :relationships, only: [:create, :destroy]
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length:{maximum: 140}
  has_many :likes, foreign_key: "micropost_id", dependent: :destroy
  has_many :comments, foreign_key: "micropost_id", dependent: :delete_all


  # いいね！
  def like(user)
    likes.create(user_id: user.id)
  end

  # いいね！取り消し
  def unlike(user)
    likes.find_by(user_id: user.id).destroy
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
    before_action :logged_in_user, only:[:create, :destroy]
    before_action :correct_user,   only: :destroy

    def show
        @micropost = Micropost.find(params[:id])
        @comments = Comment.where(micropost_id: params[:id])
    end

    def create
        @micropost = current_user.microposts.new(micropost_params)
        if @micropost.save
            flash[:success] = "Micropost created!"
            redirect_to root_url
        else
            @feed_items = []
            render "static_pages/home"
        end
    end

    def destroy
        @micropost.destroy
        flash[:success] = "Micropost deleted"
        redirect_to root_url
    end


    private

        def micropost_params
            params.require(:micropost).permit(:content)
        end

        def correct_user
            @micropost = current_user.microposts.find_by(id: params[:id])
            redirect_to root_url if @micropost.nil?
        end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <%= link_to micropost.content, micropost, class: "micropost-content"%>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  </span>
  <% if current_user?(micropost.user) %>
    <%= link_to "delete", micropost, method: :delete, data: {confirm: "You sure?"} %>
  <% end %>
  <span class="like">
    <%= render "likes/like_form", micropost: micropost %>
  </span>
  <span class="comment">
    <%= link_to new_micropost_comment_path(micropost) do%>
        <span class="glyphicon glyphicon-comment"></span>
    <% end %>
  </span>
</li>

app/views/microposts/show.html.erb
<ul class="show-microposts">
    <%= render "microposts/micropost", micropost: @micropost %>
</ul>
<ul class="comments">
    <% @comments.each do |comment| %>
        <%= render "comments/comment", comment: comment %>
    <% end %>
</ul>